---
- name: Include Vars.
  include_vars: "vars.yml"

- name: Define php version for ioncube.
  set_fact:
    magentotools_install_ioncube_php_version: "{{ __magentotools_install_ioncube_php_version }}"
  when: magentotools_install_ioncube_php_version is not defined
#magerun
- name: Install magerun
  become: yes
  get_url: url=http://files.magerun.net/n98-magerun.phar dest=/usr/local/bin/magerun mode=0755
  when: magentotools_install_magerun
#Modman
- name: Install modman
  become: yes
  get_url: url=https://raw.githubusercontent.com/colinmollenhour/modman/master/modman dest=/usr/local/bin/modman mode=0755
  when: magentotools_install_modman
#Composer
- name: Download Composer installer
  become: yes
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: magentotools_install_composer
- name: Install  Composer
  become: yes
  command: php /tmp/composer-installer.php --install
  when: magentotools_install_composer
- name: Move composer
  become: yes
  shell: mv composer.phar /usr/local/bin/composer
  when: magentotools_install_composer
#Composer IonCube
- name: Download IonCube for php
  become: yes
  get_url: url=http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz dest=/tmp mode=0755
  when: magentotools_install_ioncube
- name: Unarchive IonCube for php
  become: yes
  unarchive: src=/tmp/ioncube_loaders_lin_x86-64.tar.gz dest=/usr/local/bin copy=no
  when: magentotools_install_ioncube
- name: Set up IonCube in php-fpm
  template:
    src: 00-ioncube.j2
    dest: "/etc/php/{{ magentotools_install_ioncube_php_version }}/fpm/conf.d/00-ioncube.ini"
    mode: 0775
  when: magentotools_install_ioncube
  notify:
    - restart php-fpm
- name: Set up IonCube in php-cli
  template:
    src: 00-ioncube.j2
    dest: "/etc/php/{{ magentotools_install_ioncube_php_version }}/cli/conf.d/00-ioncube.ini"
    mode: 0775
  when: magentotools_install_ioncube
  notify:
    - restart nginx