---
- name: restart php-fpm
  service:
    name: "php5-fpm"
    state: restarted
- name: restart php7-fpm
  service:
    name: "php7-fpm"
    state: restarted
- name: restart nginx
  service:
    name: "nginx"
    state: restarted