---
- name: "restart php5-fpm"
  service:
    name: "php{{ magentotools_install_ioncube_php_version }}-fpm"
    state: restarted
- name: restart nginx
  service:
    name: "nginx"
    state: restarted